name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.0 # Add this line

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CalSans
      fonts:
        - asset: assets/fonts/CalSans-SemiBold.otf
    - family: SF-UI-Display
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png" # Update with your icon path