// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLGN_vuilv50OMRBSVwzZCu2iI16EbgiQ',
    appId: '1:221131832138:web:2dc86b9cc0b881063c1fb3',
    messagingSenderId: '221131832138',
    projectId: 'mini-test-331ad',
    authDomain: 'mini-test-331ad.firebaseapp.com',
    databaseURL: 'https://mini-test-331ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-test-331ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpmfWTB0iC8I9iR6qAQ5Wcoy3NwdoO7ic',
    appId: '1:221131832138:android:79c02326f27c15a23c1fb3',
    messagingSenderId: '221131832138',
    projectId: 'mini-test-331ad',
    databaseURL: 'https://mini-test-331ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-test-331ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkWZAKcTvb-OiklvsPGEhd1oiwo3qKHAs',
    appId: '1:221131832138:ios:3d304fc7991f7ffe3c1fb3',
    messagingSenderId: '221131832138',
    projectId: 'mini-test-331ad',
    databaseURL: 'https://mini-test-331ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-test-331ad.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkWZAKcTvb-OiklvsPGEhd1oiwo3qKHAs',
    appId: '1:221131832138:ios:3d304fc7991f7ffe3c1fb3',
    messagingSenderId: '221131832138',
    projectId: 'mini-test-331ad',
    databaseURL: 'https://mini-test-331ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-test-331ad.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSGIuDmYv4korFKfDzIdVNnQ9x5GjMALI',
    appId: '1:221131832138:web:16f3a63fc6f370af3c1fb3',
    messagingSenderId: '221131832138',
    projectId: 'mini-test-331ad',
    authDomain: 'mini-test-331ad.firebaseapp.com',
    databaseURL: 'https://mini-test-331ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-test-331ad.appspot.com',
  );
}
